# Multimodal VAP Evaluation Configuration
# This config extends multimodal_vap_config.yaml with evaluation-specific settings

defaults:
  - multimodal_vap_config  # Base configuration
  - _self_                 # Override with settings from this file

datamodule:
  eval_mode: true  # Enable evaluation mode for testing with single speakers

module:
  test_metric:
    _target_: vap.metrics.VAPMetric
    threshold: 0.5
    event_config:
      min_context_time: 3
      metric_time: 0.2
      metric_pad_time: 0.05
      max_time: 20
      frame_hz: 50
      equal_hold_shift: True
      prediction_region_time: 0.5
      # Shift/Hold
      sh_pre_cond_time: 1.0
      sh_post_cond_time: 1.0
      sh_prediction_region_on_active: True
      # Backchannel
      bc_pre_cond_time: 1.0
      bc_post_cond_time: 1.0
      bc_max_duration: 1.0
      bc_negative_pad_left_time: 1.0
      bc_negative_pad_right_time: 2.0
      # Long/Short
      long_onset_region_time: 0.2
      long_onset_condition_time: 1.0

# For testing, we only need to run inference, no training
trainer:
  max_epochs: 0 
  limit_test_batches: 1.0
